TEXT_GAMEOVER = "IGRA ZAVRŠENA";
TEXT_OF = "/";
TEXT_SCORE = "SCORE";
TEXT_BEST_SCORE = "TVOJ NAJBOLJI SCORE";
TEXT_MULTIPLIER = "x";
TEXT_ARE_SURE = "JESI LI SIGURAN?";
TEXT_BALL_OUT = "PROMAŠAJ";
TEXT_PAUSE = "PAUZA";
TEXT_CONGRATULATION = ["DOBRO!", "ODLIČNO!", "IZVANREDNO!!!"];
TEXT_SAVED = "ODBRANA";
TEXT_HELP = "POMERI MIŠOM ILI PRSTOM NA STRANU GDE ŽELIŠ DA ŠUTAŠ";
TEXT_DEVELOPED = "DEVELOPED BY";
var TEXT_PRELOADER_CONTINUE = "START";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Čestitamo!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 =
  " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better?";
